name: anki-docker

on:
  workflow_run:
    workflows: ["trigger-anki"]
    types: [completed]

  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  extract-version:
    name: extract version
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        run: echo "VERSION=$(curl --silent https://api.github.com/repos/ankitects/anki/releases | jq -r 'first | .tag_name')" >> $GITHUB_OUTPUT
        id: extract_version
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}

  publish-sync-server-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    needs: extract-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ankitects/anki
          ref: ${{ needs.extract-version.outputs.VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs/syncserver/Dockerfile
          no-cache: true
          build-args: |
            ANKI_VERSION=${{ needs.extract-version.outputs.VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}-anki-syncserver:latest
            ${{ env.REGISTRY }}/${{ github.repository }}-anki-syncserver:${{ needs.extract-version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
