name: trigger-anki

on:
  schedule:
    - cron:  '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Make sure the code is present

      - name: List files
        run: ls

      - name: Run Anki trigger script
        run: ./trigger_anki.sh

