name: trigger-anki

on:
  schedule:
    - cron:  '0 0 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: ./trigger_anki.sh
